version: '3.8'
services:

  ##### IMAGES #####
  calendar-service:
    build:
      context: ./calendar-service
      dockerfile: Dockerfile
    image: calendar-service:latest
    container_name: calendar-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/calendar_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      - calendar-db
    networks:
      - backend

  user-management:
    build:
      context: ./user-management
      dockerfile: Dockerfile
    image: user-management:latest
    container_name: user-management
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3307/user_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      - user-db
    networks:
      - backend

  notifications:
    build:
      context: ./notifications
      dockerfile: Dockerfile
    image: notifications:latest
    container_name: notifications
    ports:
      - "8083:8080"
    depends_on:
      - user-management
      - rabbitmq
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-management
      - calendar-service
      - notifications
    networks:
      - backend
    volumes:
      - ./frontend:/app/frontend

  ##### DATABASES #####
  calendar-db:
    image: mysql:8.0
    container_name: calendar-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: calendar_db
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - calendar-db-data:/var/lib/mysql
      - ./db_scripts:/scripts
    command: ["mysqld", "--init-file=/scripts/migrate_calendar.sql"]

  user-db:
    image: mysql:8.0
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_db
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    networks:
      - backend
    volumes:
      - user-db-data:/var/lib/mysql
      - ./db_scripts:/scripts
    command: ["mysqld", "--init-file=/scripts/migrate_user.sql"]

networks:
  backend:
    driver: bridge

volumes:
  calendar-db-data:
    driver: local
  user-db-data:
    driver: local
