package com.dawe1002.user_management.service.accessingdatamysql;
import com.dawe1002.user_management.service.security.JwtUtil;

import java.util.Map;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.ResponseBody;


@RestController // This means that this class is a Controller
@RequestMapping(path = "/api/users") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

@PostMapping(path = "/login")
    public ResponseEntity<Map<String, String>> loginUser(
            @RequestBody Map<String, Object> body
    ) {
        String email = body.get("email").toString();
        String password = body.get("password").toString();

        Optional<User> optionalUser = userRepository.findByEmail(email);

        if (optionalUser.isEmpty() ||
            !password.equals(optionalUser.get().getPasswort())) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
        }

        User user = optionalUser.get();
        //JWT erzeugen
        String token = JwtUtil.generateToken(user.getId());
        //Token in DB speichern
        user.setToken(token);
        userRepository.save(user);

        return ResponseEntity.ok(Map.of("token", token));
    }

@PostMapping("/logout")
  public ResponseEntity<Void> logout(
          @RequestHeader("Authorization") String authHeader
  ) {
      if (authHeader == null || !authHeader.startsWith("Bearer ")) {
          return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
      }

      String token = authHeader.substring(7);

      Optional<User> userOpt = userRepository.findByToken(token);

      if (userOpt.isPresent()) {
          User user = userOpt.get();
          user.setToken(null);
          userRepository.save(user);
      }

      return ResponseEntity.ok().build();
  }


  @PostMapping(path = "/register")
  public ResponseEntity<String> registerUser(@RequestBody Map<String, Object> body) {
	  String vorname = body.get("vorname").toString();
	  String nachname = body.get("nachname").toString();
	  String email = body.get("email").toString();
	  String password = body.get("password").toString();

    User n = new User();
    n.setVorname(vorname);
    n.setNachname(nachname);
    n.setEmail(email);
    n.setPasswort(password);
    
    try {
    	userRepository.save(n);
    	return ResponseEntity.ok("Registrierung erfolgreich!");
    } catch (DataIntegrityViolationException e) {
    	return ResponseEntity.status(HttpStatus.CONFLICT).body("Email-Adresse bereits vergeben");       
    }
}


  @GetMapping(path="/all")
  public @ResponseBody Iterable<User> getAllUsers() {
    return userRepository.findAll();
  }
}