package com.dawe1002.calendar.service.accessingdatamysql;

import java.util.Map;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/api/calendar") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private TerminRepository terminRepository;

  
  // TODO use @RequestBody to read POST data from body instead of URL params
  @PostMapping(path = "/add")
  public ResponseEntity<String> addAppointment(@RequestBody Map<String, Object> body) {
	  String titel = body.get("titel").toString();
	  String beschreibung = body.get("beschreibung").toString();
	  String termin_datetime = body.get("termin_datetime").toString();
    // @RequestParam means it is a parameter from the GET or POST request

    Termin n = new Termin();
    n.setTitel(titel);
    n.setBeschreibung(beschreibung);
    n.setTermin_datetime(termin_datetime);
    try {
    	terminRepository.save(n);
    	return ResponseEntity.ok("Termin erfolgreich angelegt!");
    } catch (DataIntegrityViolationException e) {
    	return ResponseEntity.status(HttpStatus.CONFLICT).body("Fehler: Termin nicht angelegt!");        
    }
  }
  
  @PostMapping(path = "/delete")
  public ResponseEntity<String> deleteAppointment(@RequestBody Map<String, Object> body) {  
      try {
          Integer termin_id = Integer.parseInt(body.get("termin_id").toString());

          if (!terminRepository.existsById(termin_id)) {
              return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Fehler: Termin nicht gefunden!");
          }
          if (terminRepository.existsById(termin_id)) {
              terminRepository.deleteById(termin_id);
              return ResponseEntity.status(HttpStatus.OK).body("Termin wurde erfolgreich gelöscht!");
          } else {
              return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Fehler: Termin nicht gefunden!");
          }
      } catch (NumberFormatException | NullPointerException e) {
          return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("Ungültige Termin-ID!");
      }
  }



  @GetMapping(path="/all")
  public @ResponseBody Iterable<Termin>  getAllAppointments() {
    // This returns a JSON or XML with the users
    return terminRepository.findAll();
  }
}